#
# Makefile para os programas de teste, gerando executáveis na pasta bin
#

CC=gcc
LIB_DIR=../lib/
BIN_DIR=../bin/

all: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12

test1: test1.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test1 test1.c -L$(LIB_DIR) -lt2fs -Wall

test2: test2.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test2 test2.c -L$(LIB_DIR) -lt2fs -Wall

test3: test3.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test3 test3.c -L$(LIB_DIR) -lt2fs -Wall

test4: test4.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test4 test4.c -L$(LIB_DIR) -lt2fs -Wall

test5: test5.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test5 test5.c -L$(LIB_DIR) -lt2fs -Wall

test6: test6.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test6 test6.c -L$(LIB_DIR) -lt2fs -Wall

test7: test7.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test7 test7.c -L$(LIB_DIR) -lt2fs -Wall

test8: test8.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test8 test8.c -L$(LIB_DIR) -lt2fs -Wall

test9: test9.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test9 test9.c -L$(LIB_DIR) -lt2fs -Wall

test10: test10.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test10 test10.c -L$(LIB_DIR) -lt2fs -Wall

test11: test11.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test11 test11.c -L$(LIB_DIR) -lt2fs -Wall

test12: test12.c $(LIB_DIR)libt2fs.a
	$(CC) -o $(BIN_DIR)test12 test12.c -L$(LIB_DIR) -lt2fs -Wall

clean:
	rm -rf $(BIN_DIR)test1 $(BIN_DIR)test2 $(BIN_DIR)test3 $(BIN_DIR)test4  $(BIN_DIR)test5  $(BIN_DIR)test6 $(BIN_DIR)test7  $(BIN_DIR)test8  $(BIN_DIR)test9  $(BIN_DIR)test10  $(BIN_DIR)test11  $(BIN_DIR)test12
